In [4]:
import numpy as np
from scipy.optimize import linprog
from basic_utils import nn2na

# Node-Node matrix
NN = np.array([[0, 1, 1, 0, 0, 0],   #s
               [0, 0, 0, 1, 0, 1],   #2
               [0, 0, 0, 0, 1, 0],   #3
               [0, 0, 0, 0, 0, 1],   #4
               [0, 0, 0, 0, 0, 1],   #5
               [0, 0, 0, 0, 0, 0]])  #t
                     

# A matrix, which is Node-arc matrix. Arcs is a tuple with dim(arcs) = #arcs in the graph
Aeq, arcs = nn2na(NN) 
t = [[3, 1, 3, 1, 3, 3, 5]]

# Cost matrix. Dim(C) = #Arcs
C = [2, 1, 2, 5, 2, 1, 2]

# b Vector. Dim(b) = #nodes
beq = [1, 0, 0, 0, 0, -1]
T = [10,9, 8]

# Bounds: 0 por lower, Inf for Upper.
bounds = tuple([(0, None) for arc in range(0, Aeq.shape[1])])
    
print("Input arguments:\n\n",
"\n- Aeq matrix:\n", Aeq,
"\n- Cost matrix: \n", C,
"\n- b vector: \n", beq,
"\n- beq vector: \n", beq,
"\n- Bounds: \n", bounds
)

for j in range(len(T)):
    
    #OPTIMIZE:
    result = linprog(C, A_ub=t, b_ub=T[j], A_eq=Aeq, b_eq=beq, bounds=bounds, method='simplex')

    print("\nResults:")
    print("\nQuantities sent through each arc: ")
    for i in range(len(result.x)):
        print(arcs[i], "->", result.x[i].astype(int))
    print("\nCost: ", result.fun)
    
    res = True in (ele == 1 for ele in result.x) 
    print("Is it possible to reach node t in time", T[j], ": ", res)



Input arguments:

 
- Aeq matrix:
 [[ 1  1  0  0  0  0  0]
 [-1  0  1  1  0  0  0]
 [ 0 -1  0  0  1  0  0]
 [ 0  0 -1  0  0  1  0]
 [ 0  0  0  0 -1  0  1]
 [ 0  0  0 -1  0 -1 -1]] 
- Cost matrix: 
 [2, 1, 2, 5, 2, 1, 2] 
- b vector: 
 [1, 0, 0, 0, 0, -1] 
- beq vector: 
 [1, 0, 0, 0, 0, -1] 
- Bounds: 
 ((0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None))

Results:

Quantities sent through each arc: 
(0, 1) -> 0
(0, 2) -> 1
(1, 3) -> 0
(1, 5) -> 0
(2, 4) -> 1
(3, 5) -> 0
(4, 5) -> 1

Cost:  5.0
Is it possible to reach node t in time 10 :  True

Results:

Quantities sent through each arc: 
(0, 1) -> 0
(0, 2) -> 1
(1, 3) -> 0
(1, 5) -> 0
(2, 4) -> 1
(3, 5) -> 0
(4, 5) -> 1

Cost:  5.0
Is it possible to reach node t in time 9 :  True

Results:

Quantities sent through each arc: 
(0, 1) -> 0
(0, 2) -> 0
(1, 3) -> 0
(1, 5) -> 0
(2, 4) -> 0
(3, 5) -> 0
(4, 5) -> 0

Cost:  5.4
Is it possible to reach node t in time 8 :  False
